### ISSUE TITLE
Shared Hosting – Tutorial

### ISSUE THREAD

**Issue by shmith** [ME1312/SubServers-2#20]
Hey there,

I was wondering would you be able to detail the process of how this could possibly be done on shared hosting? I want to actually try and get SubServers.Bungee and SubServers.Host to work on my shared hosting but your tutorial seems to be more focused on working with your own dedicated machine.

Is there any tutorial that you could provide me with?

**Comment by ME1312** [comment]
Shared hosting is very hit or miss when it comes to SubServers 2. While it *may* be possible depending on what host you chose, it is difficult because you simply aren't in control of the machine your working with. I recommend renting a VPS or something similar.

As far as I'm aware, there have been no tutorials made at this point for using SubServers 2 on shared hosting.
