### ISSUE TITLE
Block Indentation Indicator instead of `\n`

### ISSUE THREAD

**Issue by xXSchrandXx** [ME1312/SubServers-2#38]
### What Should Be Added
Changing to `\n` to a Block Scalar `|` or `>`

Example:
``` YAML
  'Bungee.Server.Hover': '$int$ player(s)\n&oClick to connect to the server'
```
to:
``` YAML
  'Bungee.Server.Hover': |-
   $int$ player(s)
   &oClick to connect to the server
```

### Why It Should be Added
Could help making the lang.yml clearer.

### What's The Alternative
Using `\n`

Source: [YAML.org](https://yaml.org/spec/1.2/spec.html#id2794534)

**Comment by ME1312** [comment]
I suppose this makes sense. Although this formatting is valid within SubServers (and some of my other apps) because of how [non-raw strings are parsed,](https://github.com/ME1312/SubServers-2/blob/master/SubServers.Bungee/src/net/ME1312/SubServers/Bungee/Library/Util.java#L409-L436) it strays far from the yaml standard.

However formatting like that might make the config more intimidating, since as of now it's a clean one entry per line.
