### ISSUE TITLE
BungeeCord Log-DIR

### ISSUE THREAD

**Issue by xXSchrandXx** [ME1312/SubServers-2#43]
### What Should Be Added
BungeeCord Logs are quiet massive after some time. Maybe you can move them to a `logs` folder with different time quotes.

### Why It Should be Added
Just a idea...
I don't know any standalone wich does affect the logger.

### What's The Alternative
I don't know a plugin wich is able to move them to a real folder.

**Comment by ME1312** [comment]
You might want to take this one up with the [BungeeCord](https://github.com/SpigotMC/BungeeCord) and/or [Waterfall](https://github.com/PaperMC/Waterfall) devs. Of the two, I think Waterfall would be more likely to implement this feature if you were to ask for it.

The reason I say this is because SubServers does not handle logging in any form or fashion. That's all in the fork of BungeeCord you're using.

**Comment by xXSchrandXx** [comment]
I'm using [HexaCord](https://github.com/HexagonMC/BungeeCord), gonna create a Feature Request there 😄
