### ISSUE TITLE
SubServers.Host jail

### ISSUE THREAD

**Issue by xXSchrandXx** [ME1312/SubServers-2#46]
### What Should Be Added
It would be great to have a option to "jail" a SubServers.Host so he can't cmd / stop / start SubServers wich are not under this host.

### Why It Should be Added
Servermanager could set speciffic servers for builder and developer without letting them destroy main servers.

**Comment by ME1312** [comment]
This doesn't make too much sense when we're talking about console access. However, in-game command permissions could be improved upon.

However, SubServers.Client commands (and their back-end packets) aren't quite structured for this kind of thing at this time. Right now, we are limited is only per-server action permissions because that's all it knows; it doesn't know what host or groups a given server belongs to.

If BungeeCord's permission system is robust enough to allow me to do so while keeping multi-proxy support, I'd rather make the permissions be proxy-based so that I have better access to these variables.

**Comment by ME1312** [comment]
Multiple servers can now be selected using the new permission formatting as of the latest snapshot. Refer to [Commands & Permissions](https://github.com/ME1312/SubServers-2/wiki/Commands-and-Permissions) for exact details.
