### ISSUE TITLE
Improvements for /sub update

### ISSUE THREAD

**Issue by compieter-gh** [ME1312/SubServers-2#50]
### What Should Be Added
A way too update all servers too the latest version at once or a selection of servers.
A way too change the templates from spigot to paper for example.
And auto stop/start when updating the servers with custom stop messages/alert for stopping the server and config options.

### Why It Should be Added
It makes it easier too manage all the server if you have a lot of them with the same version.

/sub update (server) (version) as far as i know it only updates one server at the time and you have too manually stop/start it too which is kinda annoying if you have a lot of servers.

### What's The Alternative
I have an layout like this in mind /sub update (server1,server2,etc) (template) (version) or something similar too that.

and for all servers at once /sub update (template) (version).

**Comment by ME1312** [comment]
Switching templates is a process that should probably stay manual, since *most* templates will probably not be compatible with each-other for one reason or another.

As for selecting multiple servers, this is does seem like something that could be improved, however for templates such as `Spigot` you would want to update one server first to get a cached version before moving on to the rest.

As a side note, presently, some commands that are less resource-intensive support a wildcard (`*`) to select all servers, although, that might not be what your looking for.

This may also tie in with #46 (permissions that select multiple servers).

**Comment by ME1312** [comment]
*Progress!* I made the formatting you can expect available on this [~unfinished~ wiki page](https://github.com/ME1312/SubServers-2/wiki/Commands-and-Permissions#selecting-multiple-servers). Since it can make use of groups, a feature that you can set up right now, I thought I'd let you know ahead-of-time.

This formatting is still in the process of making it's way through the SubServers apps, though, so it isn't in the latest snapshots just yet.

**Comment by compieter-gh** [comment]
yes! okay thanks i will test it when it's available in snapshots

**Comment by ME1312** [comment]
Multiple servers can now be selected using the new command formatting as of the latest snapshot. Refer to [Commands & Permissions](https://github.com/ME1312/SubServers-2/wiki/Commands-and-Permissions) for exact details.
