### ISSUE TITLE
Velocity support

### ISSUE THREAD

**Issue by ChipWolf** [ME1312/SubServers-2#64]
### What Should Be Added
Velocity support in addition to BungeeCord support

### Why It Should be Added
Many networks use Velocity rather than BungeeCord & could benefit from SubServers

### What's The Alternative
Manually doing everything SubServers does

**Comment by ME1312** [comment]
The problem with this is that Velocity is no simple BungeeCord fork. It is its own separate code base, in fact. Which would mean what you're asking for is a rewrite of `SubServers.Bungee` and/or `SubServers.Sync`.

~~So, this probably just isn't going to happen until SubServers 3... or until Velocity sees wider adoption.~~ They're currently at 2% of the market in that regard (according to bstats.org).

**Comment by ME1312** [comment]
After further consideration, I have decided that only `SubServers.Sync` is required to achieve this in our current state. And so, I will be moving this feature up to 2.18 at the latest. This is possible because:
* The code there isn't nearly as married to BungeeCord as SubServers.Bungee
* We don't require you to actually proxy players through SubServers.Bungee
* SubServers.Sync already has platform-agnostic branding
* Introducing a new type of app is not necessary, so there should be no added confusion

Followers of this thread will be notified when a snapshot build containing the universal jar is available. Devs should expect a seperate, but similar API alongside the following common APIs you may already be familiar with: SubServers.Client.Common, SubDataClient, GalaxiUtil, etc.

**Comment by ME1312** [comment]
The first snapshot build of this is now available. There are a few missing features (notably, listener attribute syncing), but it should provide the same general functionality. For installation instructions, visit [this updated wiki page](https://github.com/ME1312/SubServers-2/wiki/Installation#SubServersSync).

This topic will remain pinned until those missing features get added, but further bug reports and such should be reported as separate issues.

**Comment by kubo6472** [comment]
Just wanted to ask this :)

**Comment by ChipWolf** [comment]
@ME1312 we exclusively use velocity, do I need to run a bungee server for subdata still?

**Comment by ME1312** [comment]
Yes, for this the controller instance (SubServers.Bungee) must be run separately &mdash; which you'd probably want to do anyway if you care about multi-proxy, uptime, etc.

**Comment by ChipWolf** [comment]
> 
> 
> Yes, for this the controller instance (SubServers.Bungee) must be run separately — which you'd probably want to do anyway if you care about multi-proxy, uptime, etc.

Absolutely, any plans to have a standalone SubData?

**Comment by ME1312** [comment]
I was thinking that if I were to rewrite again that I'd move it over to GalaxiEngine, but for now I don't really see the need to. In your case, I'd expect BungeeCord to be pretty light-weight since it's going to be doing mostly nothing.

**Comment by samuelh2005** [comment]
[Waterfall](https://papermc.io/software/waterfall) (a fork of BungeeCord with better performance) is now dead its probably a good idea to have SubServers.Bungee be rewritten (if there's time) now.
