### ISSUE TITLE
Add autostart on join using /server

### ISSUE THREAD

**Issue by pikesthefish** [ME1312/SubServers-2#84]
### What Should Be Added
Describe what you'd like to see added here.

A autostart feature that starts the server on "/server"  join with a message telling that it is starting up

### Why It Should be Added
Tell us why you think it should be added. Be sure to include reasons why everyone else would find it useful as well.

It should be added because it's kinda tedious to write "/sub start (server)" and no alternatives are all in one like Subservers 2

### What's The Alternative
Describe alternative methods that may already exist right now that accomplish the same goal, and why they suck.

The alternative is mcSleepingServerStarter and it sucks (errors, bad config for bungeecord and more bs in it)

**Comment by ME1312** [comment]
> it's kinda tedious to write "/sub start (server)"

Well, that is kinda what Bukkit's [aliases feature](https://bukkit.fandom.com/wiki/Commands.yml) is for ...

As for the more specific functionality of allowing any random user to start up and connect to a server, I think [server signs](https://github.com/ME1312/SubServers-2/wiki/Commands-and-Permissions#using-server-signs) (which were new in 2.19) would probably still handle it better (and they have support for server groupings).

**Comment by samuelh2005** [comment]
> > it's kinda tedious to write "/sub start (server)"
> 
> Well, that is kinda what Bukkit's [aliases feature](https://bukkit.fandom.com/wiki/Commands.yml) is for ...
> 
> As for the more specific functionality of allowing any random user to start up and connect to a server, I think [server signs](https://github.com/ME1312/SubServers-2/wiki/Commands-and-Permissions#using-server-signs) (which were new in 2.19) would probably still handle it better (and they have support for server groupings).

Some servers use NPCs or custom GUIs to connect to other servers. Instead of forcing them to use server signs you could have another command which allows joining to a sub server but start it as well. This can only be ran from the console with each sub server (or group) having it's own permission so you don't have "allowing any random user to start up and connect to a server".

Server owners could disallow "autostart" on some sub servers too. (Helpful for server signs too)
